services:
  processado_consumer:
    build:
      context: .
      dockerfile: dockerfile
    image: php-app
    container_name: processado_consumer
    #volumes:
    #  - .:/app
    networks:
      - gkaizen-gestor_my_network
    env_file:
      - .env
    working_dir: /app/src
    command: php processado_consumer.php

  send_consumer:
    image: php-app
    container_name: send_consumer
    #volumes:
    #  - .:/app
    networks:
      - gkaizen-gestor_my_network
    env_file:
      - .env
    working_dir: /app/src
    command: php send_consumer.php

  update_consumer:
    image: php-app
    container_name: update_consumer
    #volumes:
    #  - .:/app
    networks:
      - gkaizen-gestor_my_network
    env_file:
      - .env
    working_dir: /app/src
    command: php update_consumer.php

  upsert_consumer:
    image: php-app
    container_name: upsert_consumer
    #volumes:
    #  - .:/app
    networks:
      - gkaizen-gestor_my_network
    env_file:
      - .env
    working_dir: /app/src
    command: php upsert_consumer.php

networks:
  gkaizen-gestor_my_network:
    external: true
